services:
  db:
    image: postgres:16-alpine
    container_name: ido_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ido_manager
    ports:
      - "5432:5432"
    volumes:
      - ido_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: ido_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@ido.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
    ports:
      - "8080:80"
    depends_on:
      - db

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: ido_api
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ido_manager?schema=public
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: ido_web
    env_file:
      - .env
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  ido_pgdata:
